### ISSUE TITLE
Import & export site settings

### ISSUE THREAD

**Issue by noscript** [CptFoobar/Owl#10]
I did not find how to export and import sites blacklist.

**Comment by TigerKid001** [comment]
Yeah, that option doesn't exist right now. I'll try to add it in the next update (which has been due for a while now). Meanwhile, one way around can be to copy the config file from your Firefox profile (from where you wish to export) and paste it in the new profile/system (where you want to import).
In Windows, typically the config would be:
`C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<randomstring>.default\jetpack\@owl-comfortable-reading-addon\simple-storage\store.json`
On Linux, it should be:
`~/.mozilla/firefox/<randomstring>.default/jetpack/@owl-comfortable-reading-addon/simple-storage/store.json`
Not sure about OS X, but should be similar to Linux, depending on wherever it is installed.

**Comment by noscript** [comment]
Great, was looking for that simple storage file but couldn't find it. Thanks.

**Comment by TigerKid001** [comment]
Owl should have this functionality by default. A simple button to import/export in the settings page should do the trick. Adding to milestone [v3](https://github.com/TigerKid001/Owl/milestone/1).

**Comment by Alan-Solitar** [comment]
Working on this.

**Comment by Alan-Solitar** [comment]
@CptFoobar 

I've pretty much got import/export working.  I just have one question.  Right now, I have it where import replaces all the current settings.  Do we want this, or do we want to merge current settings with the imported settings?

**Comment by Alan-Solitar** [comment]
pull request submitted.
