### ISSUE TITLE
Addon is broken on Firefox Nightly (59.0a1)

### ISSUE THREAD

**Issue by refragable** [CptFoobar/Owl#37]
Starting within the last week Owl no longer works on Nightly. When I open the browser console I get the following errors on page load:
```
[OWL]  [OWL] Error: Error: Message manager disconnected background.js:440:9
[OWL]  [OWL] Error: Error: Missing host permission for the tab background.js:440:9
Error: Missing host permission for the tab, and any iframes undefined
```
This error persists on a fresh profile too, however after a downgrade to the Developer Edition (58.0b8) the addon works as expected.

**Comment by naman** [comment]
Doesn't seem to be working on v59.0b4 either.

**Comment by sjbronner** [comment]
I'm experiencing the same on Firefox Developer Edition 59.0b3.

My guess is that the new CSS engine used in this Firefox version (Quantum CSS) is throwing Owl for a loop.

https://hacks.mozilla.org/2017/08/inside-a-super-fast-css-engine-quantum-css-aka-stylo/
