### ISSUE TITLE
Stackoverflow goes blank

### ISSUE THREAD

**Issue by noscript** [CptFoobar/Owl#8]
When Owl enabled, Stackoverflow becomes a blank grey page.

Screenshot:
![stack](https://cloud.githubusercontent.com/assets/717109/19230557/e31498b6-8edd-11e6-9215-ef1ef4e91bb4.png)

**Comment by TigerKid001** [comment]
This is a known issue with multiple sites. I've made many attempts to fix this, but nothing worked. The only resort in such cases is to use Classic theme on these pages.

**Comment by noscript** [comment]
Reported the bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1336480

**Comment by TigerKid001** [comment]
Thanks for reporting the bug and sharing the link. I'll keep track of it's progress, see if there's something I can help with. Reopening this issue for now till the Bugzilla issue is resolved.

**Comment by TigerKid001** [comment]
Status of [bug #1336480](https://bugzilla.mozilla.org/show_bug.cgi?id=1336480) on Bugzilla has been changed to fixed for Firefox 54. Should be able to close this issue after the formal release of Fx54

**Comment by CptFoobar** [comment]
Seems fixed
